// Code generated by protoc-gen-go.
// source: gls.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	gls.proto

It has these top-level messages:
	ReqLogin
*/
package proto

import proto1 "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = math.Inf

type ReqLogin struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Pwd              *string `protobuf:"bytes,2,req,name=pwd" json:"pwd,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReqLogin) Reset()         { *m = ReqLogin{} }
func (m *ReqLogin) String() string { return proto1.CompactTextString(m) }
func (*ReqLogin) ProtoMessage()    {}

func (m *ReqLogin) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ReqLogin) GetPwd() string {
	if m != nil && m.Pwd != nil {
		return *m.Pwd
	}
	return ""
}

func init() {
}
