// Code generated by protoc-gen-go.
// source: gls.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	gls.proto

It has these top-level messages:
	ProtoHeader
	ReqLogin
	RspLogin
	ReqHeartBeat
	RspHeartBeat
*/
package pb

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

// general response protocol
type ProtoHeader struct {
	ApiVer           *string `protobuf:"bytes,1,req,name=apiVer" json:"apiVer,omitempty"`
	SessionId        *string `protobuf:"bytes,2,opt,name=sessionId" json:"sessionId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoHeader) Reset()         { *m = ProtoHeader{} }
func (m *ProtoHeader) String() string { return proto.CompactTextString(m) }
func (*ProtoHeader) ProtoMessage()    {}

func (m *ProtoHeader) GetApiVer() string {
	if m != nil && m.ApiVer != nil {
		return *m.ApiVer
	}
	return ""
}

func (m *ProtoHeader) GetSessionId() string {
	if m != nil && m.SessionId != nil {
		return *m.SessionId
	}
	return ""
}

type ReqLogin struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Pwd              *string `protobuf:"bytes,2,req,name=pwd" json:"pwd,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ReqLogin) Reset()         { *m = ReqLogin{} }
func (m *ReqLogin) String() string { return proto.CompactTextString(m) }
func (*ReqLogin) ProtoMessage()    {}

func (m *ReqLogin) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ReqLogin) GetPwd() string {
	if m != nil && m.Pwd != nil {
		return *m.Pwd
	}
	return ""
}

type RspLogin struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RspLogin) Reset()         { *m = RspLogin{} }
func (m *RspLogin) String() string { return proto.CompactTextString(m) }
func (*RspLogin) ProtoMessage()    {}

type ReqHeartBeat struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ReqHeartBeat) Reset()         { *m = ReqHeartBeat{} }
func (m *ReqHeartBeat) String() string { return proto.CompactTextString(m) }
func (*ReqHeartBeat) ProtoMessage()    {}

type RspHeartBeat struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RspHeartBeat) Reset()         { *m = RspHeartBeat{} }
func (m *RspHeartBeat) String() string { return proto.CompactTextString(m) }
func (*RspHeartBeat) ProtoMessage()    {}

func init() {
}
